// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/iam/v1/iam.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на логин. Логин может быть username или email — детали решаются на уровне сервиса.
type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`       // логин или email
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // пароль в открытом виде (хэшируется на стороне сервиса)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *SignInRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Ответ на успешный логин.
type SignInResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                           // ID сессии в Redis
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                    // ID пользователя
	ExpiresAtUnixSec int64                  `protobuf:"varint,3,opt,name=expires_at_unix_sec,json=expiresAtUnixSec,proto3" json:"expires_at_unix_sec,omitempty"` // unix-время истечения сессии (UTC), опционально для клиентов
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *SignInResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignInResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignInResponse) GetExpiresAtUnixSec() int64 {
	if x != nil {
		return x.ExpiresAtUnixSec
	}
	return 0
}

// Запрос на проверку сессии (например, из gRPC-интерцептора Inventory).
type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // ID сессии, передаваемый клиентом (например, из metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Ответ проверки сессии.
type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                // true, если сессия активна и валидна
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя, связанный с сессией (для проброса в контекст)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Запрос на получение контактных данных пользователя.
type GetUserContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContactRequest) Reset() {
	*x = GetUserContactRequest{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContactRequest) ProtoMessage() {}

func (x *GetUserContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContactRequest.ProtoReflect.Descriptor instead.
func (*GetUserContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserContactRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ с контактной информацией.
// На неделе 6 нам достаточно Telegram ID, остальные поля можно добавить позже.
type GetUserContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TelegramId    string                 `protobuf:"bytes,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"` // Telegram ID пользователя, который будет использовать Notification Service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContactResponse) Reset() {
	*x = GetUserContactResponse{}
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContactResponse) ProtoMessage() {}

func (x *GetUserContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContactResponse.ProtoReflect.Descriptor instead.
func (*GetUserContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserContactResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserContactResponse) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

var File_api_proto_iam_v1_iam_proto protoreflect.FileDescriptor

const file_api_proto_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/iam/v1/iam.proto\x12\x06iam.v1\"A\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"w\n" +
	"\x0eSignInResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x13expires_at_unix_sec\x18\x03 \x01(\x03R\x10expiresAtUnixSec\"7\n" +
	"\x16ValidateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"H\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x15GetUserContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x16GetUserContactResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\tR\n" +
	"telegramId2\xea\x01\n" +
	"\n" +
	"IAMService\x127\n" +
	"\x06SignIn\x12\x15.iam.v1.SignInRequest\x1a\x16.iam.v1.SignInResponse\x12R\n" +
	"\x0fValidateSession\x12\x1e.iam.v1.ValidateSessionRequest\x1a\x1f.iam.v1.ValidateSessionResponse\x12O\n" +
	"\x0eGetUserContact\x12\x1d.iam.v1.GetUserContactRequest\x1a\x1e.iam.v1.GetUserContactResponseB0Z.github.com/bulbahal/GoBigTech/api/iam/v1;iampbb\x06proto3"

var (
	file_api_proto_iam_v1_iam_proto_rawDescOnce sync.Once
	file_api_proto_iam_v1_iam_proto_rawDescData []byte
)

func file_api_proto_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_api_proto_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_api_proto_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_iam_v1_iam_proto_rawDesc), len(file_api_proto_iam_v1_iam_proto_rawDesc)))
	})
	return file_api_proto_iam_v1_iam_proto_rawDescData
}

var file_api_proto_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_iam_v1_iam_proto_goTypes = []any{
	(*SignInRequest)(nil),           // 0: iam.v1.SignInRequest
	(*SignInResponse)(nil),          // 1: iam.v1.SignInResponse
	(*ValidateSessionRequest)(nil),  // 2: iam.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil), // 3: iam.v1.ValidateSessionResponse
	(*GetUserContactRequest)(nil),   // 4: iam.v1.GetUserContactRequest
	(*GetUserContactResponse)(nil),  // 5: iam.v1.GetUserContactResponse
}
var file_api_proto_iam_v1_iam_proto_depIdxs = []int32{
	0, // 0: iam.v1.IAMService.SignIn:input_type -> iam.v1.SignInRequest
	2, // 1: iam.v1.IAMService.ValidateSession:input_type -> iam.v1.ValidateSessionRequest
	4, // 2: iam.v1.IAMService.GetUserContact:input_type -> iam.v1.GetUserContactRequest
	1, // 3: iam.v1.IAMService.SignIn:output_type -> iam.v1.SignInResponse
	3, // 4: iam.v1.IAMService.ValidateSession:output_type -> iam.v1.ValidateSessionResponse
	5, // 5: iam.v1.IAMService.GetUserContact:output_type -> iam.v1.GetUserContactResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_iam_v1_iam_proto_init() }
func file_api_proto_iam_v1_iam_proto_init() {
	if File_api_proto_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_iam_v1_iam_proto_rawDesc), len(file_api_proto_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_api_proto_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_api_proto_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_api_proto_iam_v1_iam_proto = out.File
	file_api_proto_iam_v1_iam_proto_goTypes = nil
	file_api_proto_iam_v1_iam_proto_depIdxs = nil
}
