services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 2s
      timeout: 3s
      retries: 15

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 20

  kafka:
    image: public.ecr.aws/bitnami/kafka:3.6.0
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - ALLOW_PLAINTEXT_LISTENER=yes

  inventory:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      GRPC_ADDR: 0.0.0.0:50051
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: appdb
      KAFKA_BROKERS: kafka:9092
    ports:
      - "50051:50051"
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_started

  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      GRPC_ADDR: 0.0.0.0:50052
      KAFKA_BROKERS: kafka:9092
    ports:
      - "50052:50052"
    depends_on:
      kafka:
        condition: service_started

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      HTTP_PORT: "8080"
      POSTGRES_DSN: postgres://postgres:postgres@db:5432/appdb?sslmode=disable
      INVENTORY_GRPC_ADDR: inventory:50051
      PAYMENT_GRPC_ADDR: payment:50052
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      inventory:
        condition: service_started
      payment:
        condition: service_started
      kafka:
        condition: service_started

  assembly:
    build:
      context: .
      dockerfile: services/assembly/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      KAFKA_BROKERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started

  notification:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      KAFKA_BROKERS: kafka:9092
      TELEGRAM_BOT_TOKEN: "8792715861:AAEY23RWOU43ABfn0V_RHNP9FyQJLNfo1mg"
      TELEGRAM_CHAT_ID: "945576559"
    depends_on:
      kafka:
        condition: service_started

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  iam:
    build:
      context: .
      dockerfile: services/iam/Dockerfile
    restart: unless-stopped
    environment:
      ENV: local
      GRPC_ADDR: 0.0.0.0:50060
      POSTGRES_DSN: postgres://postgres:postgres@db:5432/iamdb?sslmode=disable
      REDIS_ADDR: redis:6379
    ports:
      - "50060:50060"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db-data:
  mongo-data:
  redis-data: